version: 2.1
jobs:
  security-checks:
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout
      - run:
          name: Run SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.login=$SONAR_TOKEN
workflows:
  version: 2
  security:
    jobs:
      - security-checks