version: 2.1
orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@3.0.0

jobs:
  security-checks:
    docker:
      - image: cimg/node:18.20.2
    steps:
      - checkout
      - run:
          name: Install SonarScanner Locally
          command: |
            npm install sonar-scanner --save-dev
      - run:
          name: Fix SonarScanner Permissions
          command: |
            chmod +x ./node_modules/sonar-scanner/bin/sonar-scanner
      - run:
          name: Run SonarCloud Scan
          command: |
            npx sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  security:
    jobs:
      - security-checks
