version: 2.1
# ... (rest of your config remains unchanged)
jobs:
  # ... (other jobs remain unchanged)
  run-security-tests:
    docker:
      - image: cimg/node:18.20.5
    working_directory: ~/project/server
    steps:
      - checkout
      # ... (other steps remain unchanged)
      - run:
          name: Generate backend certs
          command: |
            mkdir -p certs
            openssl req -x509 -nodes -days 1 -newkey rsa:2048 \
              -keyout certs/backend-key.pem \
              -out certs/backend-cert.pem \
              -subj "/CN=localhost"
      - run:
          name: Debug certs directory
          command: ls -l certs
      - run:
          name: Run security tests
          command: npm run test:security
      # ... (rest of steps remain unchanged)
workflows:
  version: 2
  build-and-test:
    jobs:
      # ... (other jobs remain unchanged)
      - run-security-tests
